opencocon v9e changes - some packages version up'd - some bugfix

diff --git a/meta-cocon/recipes-core/opencocon-init/files/rcS b/meta-cocon/recipes-core/opencocon-init/files/rcS
--- a/meta-cocon/recipes-core/opencocon-init/files/rcS
+++ b/meta-cocon/recipes-core/opencocon-init/files/rcS
@@ -25,8 +25,35 @@ mount tmpfs /tmp -t tmpfs
 # tmp : mount root filesystem
 mount -o remount,rw /
 
-# TODO: move to right place
-# depmod -a
+if [ "` cat /proc/cmdline | grep sqs-netboot`" ];
+then
+  # TODO : Cleanup and devide to common scripts.
+  [ -c /dev/zero ] || mount -t devtmpfs devtmpfs /dev
+  touch /run/write_check 2> /dev/null || {
+    mount -t tmpfs none /mnt/ram
+
+    mkdir /mnt/ram/volatile
+    mount -bind /mnt/ram/volatile /var/volatile
+    mkdir /var/volatile/tmp
+    mkdir /var/volatile/log
+    mkdir /var/volatile/run
+    mkdir /var/volatile/run/dbus
+    mkdir /var/volatile/lock
+
+    mkdir /mnt/ram/run
+    mount -bind /mnt/ram/run /run
+
+    mkdir /mnt/ram/etc
+    mount -t aufs -o br:/mnt/ram/etc:/etc none /etc
+
+    mkdir /mnt/ram/home
+    mount -t aufs -o br:/mnt/ram/home:/home none /home
+  }
+  rm -f /run/write_check
+
+  COCON_SQS_NETBOOT=1
+  export COCON_SQS_NETBOOT
+fi
 
 #
 #	See if system needs to be setup. This is ONLY meant to
